sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10

  alioss:
    access-key-id:
    access-key-secret:
    bucket-name:
    endpoint:
  wechat:
    appid:
    secret:
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\apiclient_key.pem
    privateKeyFilePath:
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    weChatPayCertFilePath:
    notifyUrl: https://68c39b57.r21.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://68c39b57.r21.cpolar.top/notify/refundSuccess
