sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    access-key-id: LTAI5tHDMcPKANSrvsCbc8cD
    access-key-secret: esZ5Dah4u3t4TsoEypHmMgSiS9JM6W
    bucket-name: sky-take-out-wzf
    endpoint: oss-cn-beijing.aliyuncs.com